build:
  jsunit:
    image: nextcloudci/jsunit:1.0.6
    commands:
      - ./autotest-js.sh
  sqlite-php5.4:
    image: nextcloudci/php5.4:1.0.7
    commands:
      - rm -rf data/* config/config.php # TODO: remove this - temporary fix for CI issues
      - git submodule update --init
      - NOCOVERAGE=true ./autotest.sh sqlite
  sqlite-php5.5:
    image: nextcloudci/php5.5:1.0.7
    commands:
      - rm -rf data/* config/config.php # TODO: remove this - temporary fix for CI issues
      - git submodule update --init
      - NOCOVERAGE=true ./autotest.sh sqlite
  sqlite-php5.6:
    image: nextcloudci/php5.6:1.0.6
    commands:
      - rm -rf data/* config/config.php # TODO: remove this - temporary fix for CI issues
      - git submodule update --init
      - NOCOVERAGE=true ./autotest.sh sqlite
  sqlite:
    image: nextcloudci/php7.0:1.0.10
    commands:
      - rm -rf data/* config/config.php # TODO: remove this - temporary fix for CI issues
      - git submodule update --init
      - NOCOVERAGE=true ./autotest.sh sqlite
  mysql:
    image: nextcloudci/php7.0:1.0.10
    commands:
      - sleep 15 # gives the database enough time to initialize
      - rm -rf data/* config/config.php # TODO: remove this - temporary fix for CI issues
      - git submodule update --init
      - NOCOVERAGE=true ./autotest.sh mysql
  postgres:
    image: nextcloudci/php7.0:1.0.10
    commands:
      - sleep 10 # gives the database enough time to initialize
      - rm -rf data/* config/config.php # TODO: remove this - temporary fix for CI issues
      - git submodule update --init
      - NOCOVERAGE=true ./autotest.sh pgsql
  integration:
    image: nextcloudci/php7.0:1.0.10
    commands:
      - rm -rf data/* config/config.php # TODO: remove this - temporary fix for CI issues
      - git submodule update --init
      - ./occ maintenance:install --admin-pass=admin
      - cd build/integration
      - ./run.sh

compose:
  cache:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=oc_autotest
      - POSTGRES_PASSWORD=oc_autotest
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=oc_autotest
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=oc_autotest
